### PR TITLE
Feature/second archetype

### PR DESCRIPTION
**Pull request by ptbrown121**
I have put archetype_2 in the three places you said to put it.

I am curious about how archetype_2 is linked with the archetype data set?  I have spent some time looking for this and I don't see it.  I would appreciate an explanation for when this happens but I am not that hung up on it if it would take to long.

I would also like to not have to add another big header for archetype_2 in the print version to save space.  I was going to put.

                         name: "archetype",
                         display: "Archetype" + ", " + "archetype_2"

However, I wasn't sure if that would work and it would also make the comma come up no matter what.

### CODE REVIEW

**Comment by gnu-lorien** [comment]
Excellent! You've started down the rabbit hole. There's one problem that needs to be fixed before I can accept this branch.

### No archetype options appear when trying to pick your second archetype.

Go to character creation. Click on archetype_2. You don't see any available options when picking the second archetype in character creation. This means that players effectively can't choose it.

### Other Possible Improvements

There are some other things you might want to dig into though to improve how this works.

#### Enhanced Print Display

I agree that it would probably look better to show each of your Archetypes in line with one other. The idea behind the HeaderView is that all of the formatting is handled within the class. The actual display is constructed dynamically, so you can’t make the decision when setting the display variable. What you should instead try is to pass name as an array. Change the behavior inside of HeaderView to behave differently if name is an array and display the second archetype if it’s set.

#### Accidental Picks

Very few people are going to have a second archetype, but lots of people are going to accidentally click on that field. Currently there’s no way to permanently unselect a text and set it back to nothing. Maybe work on a way to “unpick” texts like the other options in character creation can be unpicked.

### Closing Thoughts

I don’t know if you noticed, but after you submitted the request there was a netlify preview that was deployed. You can click on Show All Checks to see it. This will let you check out how your code will appear in its final form against the staging DB.

**Comment by ptbrown121** [comment]
I suspected that I needed archetype_2 to point the the data file for the list of archetypes, but I don't see were the original archetype is pointing to the list of archetypes.  My suspicion is that I am missing something having to do with this line,

    Model.all_text_attributes = function () {
        return TEXT_ATTRIBUTES;

but I am not sure what to do to have archetype_2 display the archetypes.

I like the idea for changing archetype to an array I will work on that.

The short fix for people who accidentally set a second archetype would be to add an archetype option of "none", but I don't like this and will work on a way to unpick things from the information section.

I am also wondering what software I should use to run my own test branches for Yorick?

**Comment by gnu-lorien** [comment]
>  I don't see were the original archetype is pointing to the list of archetypes. 

It's in the view code. Look at the hash of the URL when you're picking simpletexts: 

#charactercreate/simpletext/archetypes/archetype/RT8FXNL8P2/pick

archetypes is the name of the category to draw the list of names from, and archetype is the name of the text attribute you set on the character.

> The short fix for people who accidentally set a second archetype would be to add an archetype option of "none", but I don't like this and will work on a way to unpick things from the information section.

Yeah using "None" as a special value on the actual data model is not a very good idea. We do that in the Backform classes because null and undefined cause problems. On the Parse objects though we want to completely remove the attribute so the value is completely unset on the server side. You should be able to follow-through the "unpick" URLs to see where that work is done. You should find yourself at a method called "unpick_from_creation" IIRC.

> I am also wondering what software I should use to run my own test branches for Yorick?

MongoDB and NodeJS. How to install those on Windows is something you'll need to look up the documentation for yourself. It shouldn't be too complicated. Once you have those up and working on your box, look at https://github.com/gnu-lorien/yorick/blob/master/dotfiles/initialize_c9.bash to see how I alter the config files and initialize the Mongo database.

If you get stuck on this part let me know. There's some documentation on the wiki but it can be tricky to get it right. I created the c9 and nitrous scripts to make it easier for people that have Windows boxes to set up Linux boxes when it's simpler to do it that way. I know it works on Windows though because my original test environment and deployment environment is Windows.

**Comment by gnu-lorien** [comment]
That update should fix the blockers. I'll probably accept this merge request this afternoon.

Do you expect that you'll be doing any major work on this over the holidays? I'm considering doing the "Accidental Picks" work myself if you aren't. I have a bunch of free time and I feel *really* close to release with your help on the whole thing.

**Comment by ptbrown121** [comment]
I will be working on it over the holidays, but feel free to work on Accidental Picks.  I have spent a fair amount of time trying to get Mongo and Node working, but I am not familiar with this level of database work although I think I have unpacked enough of that bash file that I may be able to get it to work.

In the immediate I think I am going to make a few more passes over the werewolf stuff in staging to make sure there aren't anymore significant character creation changes that have been missed.

**Pull request merged**
